name: DevSecOps CI

on:
  push:
    branches: [ master ]
  - name: Build with Maven
  run: mvn clean install -Denforcer.skip=true
      - name: OWASP Dependency Check
      
        run: mvn org.owasp:dependency-check-maven:check -Denforcer.skip=true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Docker Build
        run: docker build -t my-app .

      - name: Docker Scan
        run: echo "Scanning Docker Image..."
